x-common: &common
  network_mode: host
  restart: unless-stopped

services:
  homebridge:
    <<: *common
    container_name: homebridge
    hostname: homebridge
    image: homebridge/homebridge:latest
    environment:
      - TZ=Europe/Stockholm
    labels:
      - 'traefik.http.services.homebridge.loadbalancer.server.port=8581'
    volumes:
      - /srv/docker/stack-home/data/homebridge:/homebridge

  scrypted:
    <<: *common
    container_name: scrypted
    image: koush/scrypted:latest
    labels:
      - 'traefik.http.routers.scrypted.rule=Host(`cameras.lundmark.tech`)'
      - 'traefik.http.services.scrypted.loadbalancer.server.port=11080' # Use insecure port; Traefik handles SSL
    volumes:
      - /srv/docker/stack-home/data/scrypted:/server/volume

