x-common: &common
  network_mode: host
  restart: unless-stopped

services:
  homeassistant:
    <<: *common
    container_name: homeassistant
    image: linuxserver/homeassistant:latest
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
    labels:
      - 'traefik.http.routers.homeassistant.rule=Host(`home.lundmark.tech`)'
      - 'traefik.http.services.homeassistant.loadbalancer.server.port=8123'
      - 'com.centurylinklabs.watchtower.enable=false'
    volumes:
      - /srv/docker/stack-home/data/homeassistant:/config
      - nfs-music:/music:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  homebridge:
    <<: *common
    container_name: homebridge
    hostname: homebridge
    image: homebridge/homebridge:latest
    environment:
      - TZ=Europe/Stockholm
    labels:
      - 'traefik.http.services.homebridge.loadbalancer.server.port=8581'
    volumes:
      - /srv/docker/stack-home/data/homebridge:/homebridge

  scrypted:
    <<: *common
    container_name: scrypted
    image: koush/scrypted:latest
    labels:
      - 'traefik.http.routers.scrypted.rule=Host(`cameras.lundmark.tech`)'
      - 'traefik.http.services.scrypted.loadbalancer.server.port=11080' # Use insecure port; Traefik handles SSL
    volumes:
      - /srv/docker/stack-home/data/scrypted:/server/volume

volumes:
  nfs-music:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.0.1.2,soft,timeo=50,vers=4.1,noatime"
      device: ":/volume1/music"
