services:
  portainer-edge-agent:
    container_name: portainer_edge_agent
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/@docker/volumes:/var/lib/docker/volumes:ro
      - /:/host
      - /volume1/docker/stack-nas/data/portainer-agent:/data
    restart: always
    environment:
      - EDGE=1
      - EDGE_ID=${PORTAINER_EDGE_ID}
      - EDGE_KEY=${PORTAINER_EDGE_KEY}
      - EDGE_INSECURE_POLL=1
      - CAP_HOST_MANAGEMENT=1

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - NETWORKS=1
      - INFO=1
      - POST=0
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  dockge-agent:
    container_name: dockge-agent
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 5011:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/stack-nas/data/dockge-agent:/app/data
      - /volume1/docker:/opt/stacks
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
    volumes:
      - /volume1/docker/stack-nas/data/adguardhome/work:/opt/adguardhome/work
      - /volume1/docker/stack-nas/data/adguardhome/config:/opt/adguardhome/conf
    restart: unless-stopped
