name: 'nas-services'

services:
  portainer-edge-agent:
    container_name: portainer_edge_agent
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/@docker/volumes:/var/lib/docker/volumes:ro
      - /:/host
      - ${PROJECT_PATH}/data/portainer-agent:/data
    restart: always
    environment:
      - EDGE=1
      - EDGE_ID=${PORTAINER_EDGE_ID}
      - EDGE_KEY=${PORTAINER_EDGE_KEY}
      - EDGE_INSECURE_POLL=1
      - CAP_HOST_MANAGEMENT=1

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - NETWORKS=1
      - VOLUMES=1
      - IMAGES=1
      - INFO=1
      - POST=0 # Disable general POST endpoints for security hardening - see
      - EXEC=1
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: 'unless-stopped'
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
    volumes:
      - ${PROJECT_PATH}/data/adguardhome/work:/opt/adguardhome/work
      - ${PROJECT_PATH}/data/adguardhome/config:/opt/adguardhome/conf
    restart: unless-stopped
