api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    addRoutersLabels: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: 'home.lundmark.tech'
          - main: 'watch.lundmark.tech'
          - main: 'lundmark.tech'
            sans:
              - '*.lundmark.tech'

providers:
  docker:
    # Strip stack name and set default route to <service>.lundmark.tech
    defaultRule: 'Host(`{{ coalesce (index .Labels "com.docker.compose.service") (normalize .Name) }}.lundmark.tech`)'
  file:
    filename: /dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: g.lundmark@gmail.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: joker

serversTransport:
  insecureSkipVerify: true
